spring:
  application:
    name: kotlin-assignment
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/assignment101
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: 'update'
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 47077356499-0240bm7tji9pheu8aq3lhr8iugjdjcda.apps.googleusercontent.com
            client-secret: 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

default:
  pageSize:
    courses: 5
    departments: 5
    students: 5
    teachers: 5
  fileSave:
    dir: "D:/KotlinAssignment"
logging:
  level:
    root: info
    org.hibernate: error
    org.springframework.security: TRACE
  file:
    name: .\log-files\${spring.application.name}.log
    max-size: 11Mb
    max-history: 2
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
#    For OpenAPI - Swagger: This path needs to be provided in Swagger UI to access the endpoints
springdoc:
  api-docs:
    path: /course-management
